apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynoticeappdeployment
spec:
  selector:
    matchLabels:
      app: mynoticeapp
  #replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mynoticeapp
    spec:
      containers:
      - name: mynoticeapp
        image: noticeapp:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: notice-config-map-demo
        - secretRef:
            name: pg-pass
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynoticeapp-service
spec:
  type: NodePort
  selector:
    app: mynoticeapp
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
