version: "3"
services:
  myappdb:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: mysampleuser
      POSTGRES_PASSWORD: mysamplepwd
      POSTGRES_DB: mysampledb
    ports:
      - 33032:5432
      # - 33033:5433
    volumes:
      - C:\prac\proj_try_002\neighbourhood_notice_board\deployment\postgres-db:/var/lib/postgresql/data
    networks:
      - myappnetwork
    # command: -p 5433

  adminer:
    image: adminer
    restart: always
    ports:
      - 33080:8080
    networks:
      - myappnetwork

  mynoticeapp:
    image: noticeapp:latest
    environment:
      DB_HOST: myappdb
      DB_PORT: 5432
      DB_PASS: mysamplepwd
      DB_NAME: mysampledb
      DB_USERNAME: mysampleuser
    depends_on:
      - myappdb
    ports:
      - 8085:80
    networks:
      - myappnetwork
networks:
  myappnetwork:
